# Generated by Django 4.2.17 on 2025-02-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("project", models.CharField(max_length=200)),
                ("project_code", models.CharField(max_length=50)),
                ("activity", models.TextField()),
                (
                    "estimated_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Number of hours allocated for this task",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project Task",
                "verbose_name_plural": "Project Tasks",
                "ordering": ["-date", "project"],
            },
        ),
    ]
