# Generated by Django 4.2.17 on 2025-02-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttask",
            name="estimated_hours",
            field=models.IntegerField(
                help_text="Number of hours allocated for this task"
            ),
        ),
    ]
